name: Build the Neighbor Link Firmware

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Build Environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            curl build-essential libncurses-dev zlib1g-dev \
            gawk git gettext libssl-dev xsltproc rsync wget unzip \
            python3 python3-distutils jq

      - name: Build the Firmware
        run: |
          cd src
          bash build.bash 0.0.0

      - name: Upload Build Artifacts as a Single Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: src/build/*

  release:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: v0.0.0
            release_name: Neighbor Link Firmware v0.0.0
            draft: false
            prerelease: false
            body: |
                This is a release for the Neighbor Link Firmware.

      - name: Attach Artifacts to Release
        run: |
          for file in artifacts/*; do
            echo "Uploading $file..."
            curl -sSL -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: $(file -b --mime-type "$file")" \
              --data-binary @"$file" \
              "${{ steps.create_release.outputs.upload_url }}?name=$(basename "$file" | jq -sRr @uri)"
          done
