name: Build the Neighbor Link Firmware

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Source Release Version
        run: |
          source RELEASE_VERSION
          echo "release_version=$release_version"
          echo "release_version=$release_version" >> $GITHUB_ENV

      - name: Set up Build Environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            curl build-essential libncurses-dev zlib1g-dev \
            gawk git gettext libssl-dev xsltproc rsync wget unzip \
            python3 python3-distutils jq

      - name: Build the Firmware
        run: |
          cd src
          bash build.bash ${{ env.release_version }}
          echo "release_version=$release_version" >> build/RELEASE_VERSION

      - name: Upload Build Artifacts as a Single Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: src/build/*

  release:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts

      - name: Source Release Version
        run: |
           source artifacts/RELEASE_VERSION
           echo "release_version=$release_version"
           echo "release_version=$release_version" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.release_version }}
          release_name: Neighbor-Link v${{ env.release_version }}
          draft: false
          prerelease: false
          body: |
            This is a release for the Neighbor Link Firmware.

      - name: Attach Artifacts to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*
          tag: v${{ env.release_version }}
          file_glob: true
